# Generated by Django 3.0.4 on 2020-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria no activada'),
        ),
    ]
