# Generated by Django 3.0.4 on 2020-04-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=3, max_length=90, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
